# Check README.md for how to format this file
banners:
- name: (URB-33) HMRC banner 2026/03/27
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CT_Guidance_TAD
  page_paths:
    # frontend
    - /file-your-company-accounts-and-tax-return
    - /running-a-limited-company
    - /running-a-limited-company/taking-money-out-of-a-limited-company
    - /next-steps-for-your-business
  start_date: 2026/03/27
  end_date: 2026/04/24
- name: (URB-34) HMRC banner 2026/03/27
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_payCT_TAD
  page_paths:
    # frontend
    - /pay-corporation-tax
  start_date: 2026/03/27
  end_date: 2026/04/24
